#!/usr/bin/env bash
#
# Copyright (C) 2025, David J. Rosenbaum <djr7c4@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of version 3 of the GNU General Public License, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [[ ! -d ".git" ]]; then
    echo "This script must be run from the top-level of a git repository" >&2
    exit 1
fi

repos=("https://github.com/rolandwalker/anaphora.git master" "https://github.com/magnars/dash.el.git master" "https://github.com/rejeep/f.el.git master" "https://github.com/djr7C4/emacs-memoize.git master" "https://github.com/magnars/s.el.git master" "https://github.com/djr7C4/rem.git main")

for repo in "${repos[@]}"; do
    repo="$(echo "$repo" | cut -d -f 1)"
    branch="$(echo "$repo" | cut -d -f 2)"
    pkg_name="${repo##*/}"
    pkg_name="${pkg_name%.git}"
    git subtree add --prefix "package-source/${pkg_name}" --squash "$repo" "$branch"
done
